language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: mdbrown7079-github
    token:
      secure: 26180934cd66eaa1fd929ea800145213f3a3cf19
jdk:
  - oraclejdk8
script: ant build
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'